spring:
  application:
    name: authentication-service
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    refresh:
      enable: true
  instance:
    prefer-ip-address: true
user-service:
  url: http://user-service:8081