spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    refresh:
      enable: true
  instance:
    prefer-ip-address: true