spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/dealer
            - Path=/api/private
        #- id: negozio-service
        #  uri: lb://negozio-service
        #  predicates:
        #    - Path=/api/v1/shop**
        - id: recensione-service
          uri: lb://recensione-service
          predicates:
            - Path=/api/review**
    kubernetes:
      enabled: false
  application:
    name: api-gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}