spring:
  application:
    name: service-discovery-server
server:
  port: 8761
eureka:
  instance:
    hostname: service-discovery-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka/
