spring:
  application:
    name: ad-service
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
  cloud:
    kubernetes:
      enabled: false
server:
  port: 8084
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
