spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: bike-service
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
  cloud:
    kubernetes:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.connection.autocommit: false

server:
  port: 8088
  forward-headers-strategy: framework
  max-http-header-size=8192:
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}