spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:32000"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - OPTIONS
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-dealer
          uri: http://user-service:8081
          predicates:
            - Path=/api/dealer/**
        - id: user-service-private
          uri: http://user-service:8081
          predicates:
            - Path=/api/private/**
        - id: recensione-service
          uri: http://recensione-service:8082
          predicates:
            - Path=/api/review/**
        - id: shop-service
          uri: http://shop-service:8083
          predicates:
            - Path=/api/shop/**
        - id: ad-service-rent
          uri: http://ad-service:8084
          predicates:
            - Path=/api/adrent/**
        - id: ad-service-sell
          uri: http://ad-service:8084
          predicates:
            - Path=/api/adsell/**
        - id: bike-service
          uri: http://bike-service:8087
          predicates:
            - Path=/api/bike/**
        - id: booking-service
          uri: http://booking-service:8085
          predicates:
            - Path=/api/booking/**
        - id: appointment-service
          uri: http://appointment-service:8086
          predicates:
            - Path=/api/appointment/**
        - id: authentication-service
          uri: http://authentication-service:8090
          predicates:
            - Path=/auth/**
  application:
    name: api-gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}