spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - OPTIONS
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-dealer
          uri: lb://user-service
          predicates:
            - Path=/api/dealer/**
        - id: user-service-private
          uri: lb://user-service
          predicates:
            - Path=/api/private/**
        - id: recensione-service
          uri: lb://recensione-service
          predicates:
            - Path=/api/review/**
        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/api/shop/**
        - id: ad-service-rent
          uri: lb://ad-service
          predicates:
            - Path=/api/adrent/**
        - id: ad-service-sell
          uri: lb://ad-service
          predicates:
            - Path=/api/adsell/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/api/bike/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointment/**
    kubernetes:
      enabled: false
  application:
    name: api-gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}